/*
 * Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
 * 
 * On Wed Sep 12 14:38:13 EDT 2012
 * 
 */
#include "bluesim_primitives.h"
#include "schedule.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"

#include "mkFTop_kc705.h"

namespace bluesim
{
  
  /* Top-level module instances */
  static MOD_mkFTop_kc705 *mkFTop_kc705_instance = NULL;
  
  
  /* Schedule functions */
  
  void schedule_posedge_CLK()
  {
    MOD_mkFTop_kc705 &INST_top = *mkFTop_kc705_instance;
    if (do_reset_ticks())
    {
    }
  }
  
  /* Model creation/destruction functions */
  
  void create_model(bool master)
  {
    init_reset_request_counters();
    mkFTop_kc705_instance = new MOD_mkFTop_kc705("top", NULL);
    bk_get_or_define_clock("CLK");
    if (master)
    {
      bk_alter_clock(bk_get_clock_by_name("CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
      bk_use_default_reset();
    }
    bk_set_clock_event_fn(bk_get_clock_by_name("CLK"),
			  schedule_posedge_CLK,
			  NULL,
			  (tEdgeDirection)(POSEDGE));
    (mkFTop_kc705_instance->set_clk_0)("CLK");
  }
  void destroy_model()
  {
    delete mkFTop_kc705_instance;
    mkFTop_kc705_instance = NULL;
  }
  void reset_model(bool asserted)
  {
    (mkFTop_kc705_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
  }
  void * get_instance()
  {
    return mkFTop_kc705_instance;
  }
  
  /* Fill in version numbers */
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build)
  {
    *year = 2012u;
    *month = 1u;
    *annotation = "A";
    *build = "26572";
  }
  
  /* Get the model creation time */
  time_t get_creation_time()
  {
    
    /* Wed Sep 12 18:38:13 UTC 2012 */
    return 1347475093llu;
  }
  
  /* Control run-time licensing */
  tUInt64 skip_license_check()
  {
    return 0llu;
  }
  
  /* State dumping function */
  void dump_state()
  {
    (mkFTop_kc705_instance->dump_state)(0u);
  }
  
  /* VCD dumping functions */
  MOD_mkFTop_kc705 & mkFTop_kc705_backing()
  {
    static MOD_mkFTop_kc705 *instance = NULL;
    if (instance == NULL)
    {
      vcd_set_backing_instance(true);
      instance = new MOD_mkFTop_kc705("top", NULL);
      vcd_set_backing_instance(false);
    }
    return *instance;
  }
  void dump_VCD_defs()
  {
    (mkFTop_kc705_instance->dump_VCD_defs)(vcd_depth);
  }
  void dump_VCD(tVCDDumpType dt)
  {
    (mkFTop_kc705_instance->dump_VCD)(dt, vcd_depth, mkFTop_kc705_backing());
  }
}
