# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7k325tfbg900-1

    set ::env(BUILTIN_SYNTH) true
    source $::env(SYNTH_COMMON)/common.tcl

    rt::read_verilog {
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/SyncResetA.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/SyncFIFO.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/SyncBit.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/ResetInverter.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/rtl/mkCRC32.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/TriState.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/FIFO2.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/Verilog/Counter.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/blue7/bdw/mkGMAC.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/blue7/bdw/mkFTop_kc705.v
    /home/cms/projects/blue7/blue7test/blue7test.srcs/sources_1/imports/blue7/rtl/fpgaTop_kc705.v
  }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-7035-core980/realtime/fpgaTop_synth.xdc
    set rt::top fpgaTop
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter writeBlackboxInterface true
    rt::run_synthesis -module $rt::top

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  return -code "error" $rt::result
}
