set_property SRC_FILE_INFO {cfile:/home/cms/projects/blue7/blue7test/blue7test.srcs/constrs_1/imports/new/kc705.xdc rfile:../../../../../blue7test.srcs/constrs_1/imports/new/kc705.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT} [current_design]
set_property IOSTANDARD LVDS [get_ports sys0_clkp]
set_property src_info {type:XDC file:1 line:4 export:INPUT} [current_design]
set_property PACKAGE_PIN AD12 [get_ports sys0_clkp]
set_property src_info {type:XDC file:1 line:5 export:INPUT} [current_design]
set_property IOSTANDARD LVDS [get_ports sys0_clkn]
set_property src_info {type:XDC file:1 line:6 export:INPUT} [current_design]
set_property PACKAGE_PIN AD11 [get_ports sys0_clkn]
set_property src_info {type:XDC file:1 line:7 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports sys0_rst]
set_property src_info {type:XDC file:1 line:8 export:INPUT} [current_design]
set_property PACKAGE_PIN AB7 [get_ports sys0_rst]
set_property src_info {type:XDC file:1 line:9 export:INPUT} [current_design]
set_property PACKAGE_PIN G8 [get_ports sys1_clkp]
set_property src_info {type:XDC file:1 line:10 export:INPUT} [current_design]
set_property PACKAGE_PIN G7 [get_ports sys1_clkn]
set_property src_info {type:XDC file:1 line:14 export:INPUT} [current_design]
create_clock -period 5.000 -name sys0_clkp -waveform {0.000 2.500} [get_ports sys0_clkp]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[7]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[6]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[5]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[4]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[3]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[2]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[1]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_txd[0]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT} [current_design]
set_property PACKAGE_PIN N27 [get_ports {gmii_txd[0]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT} [current_design]
set_property PACKAGE_PIN N25 [get_ports {gmii_txd[1]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT} [current_design]
set_property PACKAGE_PIN M29 [get_ports {gmii_txd[2]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT} [current_design]
set_property PACKAGE_PIN L28 [get_ports {gmii_txd[3]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT} [current_design]
set_property PACKAGE_PIN J26 [get_ports {gmii_txd[4]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT} [current_design]
set_property PACKAGE_PIN K26 [get_ports {gmii_txd[5]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT} [current_design]
set_property PACKAGE_PIN L30 [get_ports {gmii_txd[6]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT} [current_design]
set_property PACKAGE_PIN J28 [get_ports {gmii_txd[7]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_tx_en]
set_property src_info {type:XDC file:1 line:94 export:INPUT} [current_design]
set_property PACKAGE_PIN M27 [get_ports gmii_tx_en]
set_property src_info {type:XDC file:1 line:95 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_tx_er]
set_property src_info {type:XDC file:1 line:96 export:INPUT} [current_design]
set_property PACKAGE_PIN N29 [get_ports gmii_tx_er]
set_property src_info {type:XDC file:1 line:97 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_gtx_clk]
set_property src_info {type:XDC file:1 line:98 export:INPUT} [current_design]
set_property PACKAGE_PIN K30 [get_ports gmii_gtx_clk]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[7]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[6]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[5]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[4]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[3]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[2]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {gmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT} [current_design]
set_property PACKAGE_PIN U30 [get_ports {gmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT} [current_design]
set_property PACKAGE_PIN U25 [get_ports {gmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT} [current_design]
set_property PACKAGE_PIN T25 [get_ports {gmii_rxd[2]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT} [current_design]
set_property PACKAGE_PIN U28 [get_ports {gmii_rxd[3]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT} [current_design]
set_property PACKAGE_PIN R19 [get_ports {gmii_rxd[4]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT} [current_design]
set_property PACKAGE_PIN T27 [get_ports {gmii_rxd[5]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT} [current_design]
set_property PACKAGE_PIN T26 [get_ports {gmii_rxd[6]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT} [current_design]
set_property PACKAGE_PIN T28 [get_ports {gmii_rxd[7]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rx_dv]
set_property src_info {type:XDC file:1 line:111 export:INPUT} [current_design]
set_property PACKAGE_PIN R28 [get_ports gmii_rx_dv]
set_property src_info {type:XDC file:1 line:112 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rx_er]
set_property src_info {type:XDC file:1 line:113 export:INPUT} [current_design]
set_property PACKAGE_PIN V26 [get_ports gmii_rx_er]
set_property src_info {type:XDC file:1 line:114 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rx_clk]
set_property src_info {type:XDC file:1 line:115 export:INPUT} [current_design]
set_property PACKAGE_PIN U27 [get_ports gmii_rx_clk]
set_property src_info {type:XDC file:1 line:118 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_col]
set_property src_info {type:XDC file:1 line:119 export:INPUT} [current_design]
set_property LOC W19 [get_ports gmii_col]
set_property src_info {type:XDC file:1 line:120 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_crs]
set_property src_info {type:XDC file:1 line:121 export:INPUT} [current_design]
set_property LOC R30 [get_ports gmii_crs]
set_property src_info {type:XDC file:1 line:122 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_int]
set_property src_info {type:XDC file:1 line:123 export:INPUT} [current_design]
set_property LOC N30 [get_ports gmii_int]
set_property src_info {type:XDC file:1 line:124 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_mdc]
set_property src_info {type:XDC file:1 line:125 export:INPUT} [current_design]
set_property PACKAGE_PIN R23 [get_ports mdio_mdc]
set_property src_info {type:XDC file:1 line:126 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports mdio_mdd]
set_property src_info {type:XDC file:1 line:127 export:INPUT} [current_design]
set_property PACKAGE_PIN J21 [get_ports mdio_mdd]
set_property src_info {type:XDC file:1 line:128 export:INPUT} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports gmii_rstn]
set_property src_info {type:XDC file:1 line:129 export:INPUT} [current_design]
set_property PACKAGE_PIN L20 [get_ports gmii_rstn]
set_property src_info {type:XDC file:1 line:133 export:INPUT} [current_design]
create_clock -period 8.000 -name GMII_RX_CLK -waveform {0.000 4.000} [get_ports gmii_rx_clk]
set_property src_info {type:XDC file:1 line:134 export:INPUT} [current_design]
set_input_delay -clock GMII_RX_CLK -max 5.500 [get_ports gmii_rxd*]
set_property src_info {type:XDC file:1 line:135 export:INPUT} [current_design]
set_input_delay -clock GMII_RX_CLK -min 0.500 [get_ports gmii_rxd*]
set_property src_info {type:XDC file:1 line:136 export:INPUT} [current_design]
set_input_delay -clock GMII_RX_CLK -max 5.500 [get_ports gmii_rx_dv]
set_property src_info {type:XDC file:1 line:137 export:INPUT} [current_design]
set_input_delay -clock GMII_RX_CLK -min 0.500 [get_ports gmii_rx_dv]
set_property src_info {type:XDC file:1 line:138 export:INPUT} [current_design]
set_input_delay -clock GMII_RX_CLK -max 5.500 [get_ports gmii_rx_er]
set_property src_info {type:XDC file:1 line:139 export:INPUT} [current_design]
set_input_delay -clock GMII_RX_CLK -min 0.500 [get_ports gmii_rx_er]
set_property src_info {type:XDC file:1 line:141 export:INPUT} [current_design]
create_clock -period 8.000 -name GMII_GTX_CLK -waveform {0.000 4.000} [get_ports sys1_clkp]
set_property src_info {type:XDC file:1 line:142 export:INPUT} [current_design]
set_output_delay -clock gmii_gtx_clk 2 [get_ports gmii_txd*]
set_property src_info {type:XDC file:1 line:143 export:INPUT} [current_design]
set_output_delay -clock gmii_gtx_clk 2 [get_ports gmii_tx_en]
set_property src_info {type:XDC file:1 line:144 export:INPUT} [current_design]
set_output_delay -clock gmii_gtx_clk 2 [get_ports gmii_tx_er]
