# 
# Synthesis run script generated by Vivado
# 

set_param iopl.termPlaceClean 1
read_verilog {
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/SyncResetA.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/SyncFIFO.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/SyncBit.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/SizedFIFO.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/ResetInverter.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/FIFO2.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/rtl/mkCRC32.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/TriState.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/MakeResetA.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/Verilog/Counter.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/bdw/mkSwap.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/bdw/mkGMAC.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/bdw/mkFTop_kc705.v
  /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.srcs/sources_1/imports/rtl/fpgaTop_kc705.v
}
set_property webtalk.parent_dir /home/cms/projects/blue7/blue7swap/blue7swap/blue7swap.data/wt [current_project]
synth_design -top fpgaTop -part xc7k325tffg900-1
write_checkpoint fpgaTop.dcp
report_utilization -file fpgaTop_utilization_synth.rpt
